language: python
python:
- '3.6'
- nightly
install:
- pip install -r requirements.txt
- pip install -e .
script:
- pytest
deploy:
  provider: pypi
  user: siku2
  password:
    secure: i8Hylft8AAFr7ITKK0ndk5KEaNpsvPowIq11PHb8JithZeikrRBLpE0vwiKrlb4YaOZ0d3p+RIvRA7QTKWDjxgFgwLneo6oH7mbF2ivbf4sYk4dYA48LNDTWnHHWqyZRRI497HIaNOCYxHNi2mTzlGnjpUnfjQ2CszEvXec5lH0i8Nvp6KVtbnA3ytQfIBB1X6ATUjto4cAt578Itwmsf5lFLQW/Cjky0u1859vWt1CBhBC+Ko0u3YSXdm0usu9sSIJXv12G1OwDGJE/190e6jp+RGQsdQJd4ynTNKUq52NdTbiefGxnWnFEMU50DXVhHwjujUpvQVUL2jWH2CMYQHZWnXwQ97bKCYPwapwlQfgGe19W+vorXwWOkONdX+L6wwupAr6hmH7Gc7UJ/dXdRX+LtfZeA8r8DCG0afYqZnAfWy0j6ph2IjExVSZ3G3MVSQLrex0XWanugWkPg5A8J0Ju5x+2ziaTE3HohEWof8XaSEzEXmAEFdlT0YgUWdwtfkEAyxlQX1JX6VXbWgUGDJY0yifioQuEHgz1TGmquajCM1Pgr7W0/tH2PdLTlEAP3asm/+DskE+lG9G/JVjhinw9Q5yY1SWbY9l1XPT3GPlARVKThzSoR4/sJQX50/M7GuxsCSsg2pC04x+Vc9lzMNQ9D+cZPSw3L3dXDSXuOzg=
  on:
    branch: master
