language: python
python:
  - "3.6"
  - "nightly"
install:
  - pip install -r requirements.txt
  - pip install -e .
script:
  - pytest
deploy:
  provider: pypi
  user: "siku2"
  password:
    secure: "D4WcVFEhgkNbpfj8mi04TvRlmaYPKYJ4ACkJKxhfwEkgHvz6hRaIpFLkEEjerdPV8i+6SlLYnGUwj+1pL8Zcmks2DbQDETk6cA+LIxSliWUmY4gJIn8lFUEnvEgdKB7DXM4FaWLhgr+QIqNA+xXrQyXkHNNOZYriO9rCvCiN/8CObB+GRsfg+RMzxq6KYGqf8mOquPxrTGQvsIYTSCDXr4RGCsaJwove3g0nK49pbuCmxw/CXGmUX9aUD0j8U5Bu0Opv8tMWgLSsQR8oxptuffomMROXtsMaRn0GluvFtEYgNQpw8gkHvrGurMEPM48ha1Tri9UlOe+EVx3H4lr06RiHU5HYSjQuujM7isL0kFWboviwGUWgX0pq48XZn6eHcQQbCZwKXpfgH7bq8Qe/ZSFU3wKrvwfGKi88pUwqnMPX2506N/7VfL+i0rA7qFk/IpXdozAwPH1K+Ga1JyJq8GA+gEKtk/ezdMrh4JEDPEtaLzHRu+C55j+1PTXP6pk8Il+cUiSoPrkqtb8p9G/cVFgIIHdcJZ27xd2/coNmyu8HVwiIpCBCs/E4I+R8yhUEMbYuyNYOCtU81GQIDPBQ7LIGLZ9A2PPh0/1SbiwNGnybaXS9wy/04sf+524CHLYBgmoH6vGhUnsL2C2v0GLxw0JheQLv3gAiJ3h0Wymk9/I="
  on:
    branch: master
