language: python
python:
- '3.6'
- nightly
install:
- pip install -r requirements.txt
- pip install -e .
script:
- pytest
deploy:
  provider: pypi
  user: siku2
  password:
    secure: cNBa4I3URv9j4bmTVEOy5EyRFtMVeLGR0O2W3N2Td1kps0Y/nFsJWQ5dXWWz0xwYZGT+v477xR44DNJR7PpusnlItk21OhHCFK4H1Akhr0OaU9vVHY0mhnhP9bOjKrKkuV3OBl8ug7d4duU+Iys0l1b677EPSG5IgByZEjrENAcdYzvlRGBFIIZ39nERAN5ped6VkoNxCGby3qDPXBy5Cigta8qfYSR+AqlDxRQ7xHKLQ2iLLT6ffT4abIOXLvwimsfFOKcTSj1pCCvlyZpBRHloWuXYqO4OSjn72+pe87sd85q3o7ggApSXkOzZelyI1zNu9z2xpgmcy/p5isQceSCjUBd86ROzL2ZzAongup70NRBFoDfz0Yn4tAIQXCIJfo1ssOp9VhQXwWRExBE9wbA8AqfOkZwP8NI4xfqnowCkmEsWX9zk9GBvTxdFIDeCjin3lJc7unkHxOOlaJIKCaoXt/sY2FGMbdIWpI088oxaL//Yvl9lt6VAaFwbhn1ww6xavnC0SukIzeoE/ub9b6LN27Vntn4v6U/bcEvVd7Xs/BcdUcZ+TtXYJxwMC09WyJVHEqOwARctYCExtw2jI4toGEQqdSmLY+qjGDadn4+tv1Vm7HZY9OGEL0sOoCuaA65lI+r1udbUMhWaZtW1iwfGHOduFCevJ8WJiMEyPus=
  on:
    branch: master
