language: python
python:
- '3.6'
- nightly
install:
- pip install -r requirements.txt
- pip install -e .
script:
- pytest
deploy:
  provider: pypi
  user: siku2
  password:
    secure: dKuHQb7mMpwmzu7iZjFZYggrbczd2ZnAAf4GHSANLz7rco8hsG0uHHaTdwrMqz1P7Z8Jd7qrY06yFnzjjNujxZzlTmgQrNId+IGoqAPWmb9akDnMalqpQX+y35DQOVicb4lix5e7ATAZ2qT1Japg+rO0BG90991h7ZGXrSTD1Smhr4+uGGarqmLKeMJgNe8UalqR1F0Vm2AHSO5LhvbvQiNeVpa34ztzCIw/1ZHyA9VqT7iUYCPJcLYyVHi77P6Jxfn1Bv/p/ljlbM8efPCIXaFlrlJD9xftDRwUX8Iizm0TTG0bUYVAwL4h6eWW6uvYHvjKmIRFgl718QmprFytLmGr9QHCxZzNPZUX/VtbJF5HFzj4/hzkgPkGKRL48NzD11lEqLxFcPZX2KG8PEkRcBPmAToLXP1T9C7fhxPpU6H+WEsJcIpFsk8FtLCJCbJqHWlQIsZ8uSfzAuefVhRbATgAbfkMug0YMZCM095IiG2wSqmwZsu4X7EmSjQOEcJKWjSCwwiKJdFMjYxp+/Jrm7SlmT8JraVh1d4rhBW73WrgdTagfEqXS9P1C2M9tnSpe2XA8KkI1QKgUpxEFFzV+V5uNDWkezK31jCrCvS5ExsZ/wsVBU2Tn8FLjlAtuAu6T8R/05XxK+tfPdDLKsilSxNp13e2SY/ROxAsgVkxqtg=
  on:
    branch: master
