language: python
python:
  - "3.6"
  - "nightly"
install:
  - pip install -r requirements.txt
  - pip install -e .
script:
  - pytest
deploy:
  provider: pypi
  user: "siku2"
  password:
    secure: "YZHHN2IRJMiKlpx0ruvl66zTlec6PkcsZ8Opfz0QToMTZ+2lwN2kbudqFkKd75+TnDyz8PSVtUw0+psjttGaWigy5+onttBcvD3O3To5+DDdnDS57G+Kh8M6jQjGNj5HKd2oAfFT1d0cgZl7OUF6X+A5G6ksGxPUZCxoKyMSKiU6M8VtHYoSAlnil2CDadjkGMogC0H78KhVJeTihjdkxcGGqmryLn891beUtK+FH8r1HiyQttGbhTMGLvbwipCYnDbpVKipSXcitTUHq0Pgq5BysoxEuu7AXYkGEvXirGWazEh/yyUFMZZPa11SuSIJpFG844v/L4gFy/z4a17qUIdBHruoASMB4fzEHCM01WuAHdR94IgbvJB77k8gRD5gwwY6Uag717Bz7YlY4tm0sHOof2reh59ylZ3fmfsEJnVgKMIm5ASinJB+j/K2wTxhXNeZHLjv77yHongrNRDZxA+Vth8QLaqaa3GReARFzdZnPJ2g8nneRwpih/MFlFo8WXI38XDmCheBUZ0SCfqLB3wYVjz9pOFkgjuy7+DUDNbV8rN6dgEmc42+bOfycta2PHigVfr++y36EXc0+pgldRfTkFUPSL6whcV4ClmsIGd6xRTNjOH4N4Bv0Vox2MdxBEOTHTPVj3ZuvMWEYvaYnV4slf/REEH9Au+BoXeqQyA="
  on:
    branch: master
